# -*- coding: utf-8 *-*

COUNTRIES = (
  u"United States",
  u"Afghanistan",
  u"Albania",
  u"Algeria",
  u"Andorra",
  u"Angola",
  u"Antigua and Barbuda",
  u"Argentina",
  u"Armenia",
  u"Australia",
  u"Austria",
  u"Azerbaijan",
  u"Bahamas",
  u"Bahrain",
  u"Bangladesh",
  u"Barbados",
  u"Belarus",
  u"Belgium",
  u"Belize",
  u"Benin",
  u"Bhutan",
  u"Bolivia",
  u"Bosnia and Herzegovina",
  u"Botswana",
  u"Brazil",
  u"Brunei",
  u"Bulgaria",
  u"Burkina Faso",
  u"Burundi",
  u"Cambodia",
  u"Cameroon",
  u"Canada",
  u"Cape Verde",
  u"Central African Republic",
  u"Chad",
  u"Chile",
  u"China",
  u"Colombia",
  u"Comoros",
  u"Congo",
  u"Costa Rica",
  u"C&ocirc;te d'Ivoire",
  u"Croatia",
  u"Cuba",
  u"Cyprus",
  u"Czech Republic",
  u"Denmark",
  u"Djibouti",
  u"Dominica",
  u"Dominican Republic",
  u"East Timor",
  u"Ecuador",
  u"Egypt",
  u"El Salvador",
  u"Equatorial Guinea",
  u"Eritrea",
  u"Estonia",
  u"Ethiopia",
  u"Fiji",
  u"Finland",
  u"France",
  u"Gabon",
  u"Gambia",
  u"Georgia",
  u"Germany",
  u"Ghana",
  u"Greece",
  u"Grenada",
  u"Guatemala",
  u"Guinea",
  u"Guinea-Bissau",
  u"Guyana",
  u"Haiti",
  u"Honduras",
  u"Hong Kong",
  u"Hungary",
  u"Iceland",
  u"India",
  u"Indonesia",
  u"Iran",
  u"Iraq",
  u"Ireland",
  u"Israel",
  u"Italy",
  u"Jamaica",
  u"Japan",
  u"Jordan",
  u"Kazakhstan",
  u"Kenya",
  u"Kiribati",
  u"North Korea",
  u"South Korea",
  u"Kuwait",
  u"Kyrgyzstan",
  u"Laos",
  u"Latvia",
  u"Lebanon",
  u"Lesotho",
  u"Liberia",
  u"Libya",
  u"Liechtenstein",
  u"Lithuania",
  u"Luxembourg",
  u"Macedonia",
  u"Madagascar",
  u"Malawi",
  u"Malaysia",
  u"Maldives",
  u"Mali",
  u"Malta",
  u"Marshall Islands",
  u"Mauritania",
  u"Mauritius",
  u"Mexico",
  u"Micronesia",
  u"Moldova",
  u"Monaco",
  u"Mongolia",
  u"Montenegro",
  u"Morocco",
  u"Mozambique",
  u"Myanmar",
  u"Namibia",
  u"Nauru",
  u"Nepal",
  u"Netherlands",
  u"New Zealand",
  u"Nicaragua",
  u"Niger",
  u"Nigeria",
  u"Norway",
  u"Oman",
  u"Pakistan",
  u"Palau",
  u"Palestine",
  u"Panama",
  u"Papua New Guinea",
  u"Paraguay",
  u"Peru",
  u"Philippines",
  u"Poland",
  u"Portugal",
  u"Puerto Rico",
  u"Qatar",
  u"Romania",
  u"Russia",
  u"Rwanda",
  u"Saint Kitts and Nevis",
  u"Saint Lucia",
  u"Saint Vincent and the Grenadines",
  u"Samoa",
  u"San Marino",
  u"Sao Tome and Principe",
  u"Saudi Arabia",
  u"Senegal",
  u"Serbia and Montenegro",
  u"Seychelles",
  u"Sierra Leone",
  u"Singapore",
  u"Slovakia",
  u"Slovenia",
  u"Solomon Islands",
  u"Somalia",
  u"South Africa",
  u"Spain",
  u"Sri Lanka",
  u"Sudan",
  u"Suriname",
  u"Swaziland",
  u"Sweden",
  u"Switzerland",
  u"Syria",
  u"Taiwan",
  u"Tajikistan",
  u"Tanzania",
  u"Thailand",
  u"Togo",
  u"Tonga",
  u"Trinidad and Tobago",
  u"Tunisia",
  u"Turkey",
  u"Turkmenistan",
  u"Tuvalu",
  u"Uganda",
  u"Ukraine",
  u"United Arab Emirates",
  u"United Kingdom",
  u"Uruguay",
  u"Uzbekistan",
  u"Vanuatu",
  u"Vatican City",
  u"Venezuela",
  u"Vietnam",
  u"Yemen",
  u"Zambia",
  u"Zimbabwe",
)


STATES = (
  u"Buenos Aires",
  u"Catamarca",
  u"Chaco",
  u"Chubut",
  "Cordoba",
  u"Corrientes",
  u"Entre Rios",
  u"Formosa",
  u"Jujuy",
  u"La Pampa",
  u"La Rioja",
  u"Mendoza",
  u"Misiones",
  u"Neuquen",
  u"Rio Negro",
  u"Salta",
  u"San Juan",
  u"San Luis",
  u"Santa Cruz",
  u"Santa Fe",
  u"Santiago del Estero",
  u"Tierra del Fuego",
  u"Tucuman",
  u"Otra",
)


LEVEL = (
    "Principiante",
    "Intermedio",
    "Avanzado",
)
